services:
  home:
    build: ./home
    container_name: home
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  cart:
    build: ./cart
    container_name: cart
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - "3000:3000"
    depends_on:
      - home
      - cart
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
